### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by sulimanzeen** [DevelopersSupportAR/rexom#1]
Hi,

I really like the way that you made a script and it is so useful and good. But please change your readme file. your English is so bad and we couldn't understand what you were trying to say at all. However, Try to use Grammarly or google translate next time.  Consequently, change the readme file and put more steps in instrucations

Kind Regards
SulimanZeen

**Comment by N1R0tka** [comment]
Thank you for your comment, my main language is not English, but I will try to improve the readme file in the next update of the project
