### ISSUE TITLE
مشكلة لما ابي الغي تثبيته

### ISSUE THREAD

**Issue by medofg1** [DevelopersSupportAR/rexom#10]
![Screenshot_2](https://user-images.githubusercontent.com/55420033/135832330-010017e4-cdd9-40a2-a7b6-0b941231c6c5.png)
مايطلع من الروم

**Comment by medofg1** [comment]
لكن اقدر اكيكه ومايدخل مرة ثانية

**Comment by medofg1** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/55420033/135832757-168bc8dc-df95-4f56-9e1d-f6532ca98419.png)
![Screenshot_4](https://user-images.githubusercontent.com/55420033/135832763-be7b7be1-74f5-42d5-a399-ca6f92ef7732.png)
ايرر لما اشغل

**Comment by N1R0tka** [comment]
> لكن اقدر اسويله دس كونيكت ومايدخل مرة ثانية لان سويت له leave

هاد مو خطأ البوت مصمم ليعمل بهاذه الطريقه!
