### ISSUE TITLE
مشكلة لما اشغل اغاني

### ISSUE THREAD

**Issue by medofg1** [DevelopersSupportAR/rexom#11]
![Screenshot_3](https://user-images.githubusercontent.com/55420033/135832954-a6ad9851-fba3-48e0-952c-9decc92def93.png)
![Screenshot_4](https://user-images.githubusercontent.com/55420033/135832959-4d784cfa-7eda-4f99-8405-21949175e754.png)
![Screenshot_5](https://user-images.githubusercontent.com/55420033/135832964-f5d52c7c-640e-43a1-b37f-c1e44f39158b.png)
يجي ايرر يوم اشغل

**Comment by N1R0tka** [comment]
الظاهر لي ان المشكله من عندك جرب تنسخ البوت تاني
