### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by PROMEDO** [DevelopersSupportAR/rexom#12]
![Screenshot_23](https://user-images.githubusercontent.com/55420033/136281738-15d64964-bd90-4451-aa3b-c49e358caafe.png)
اقدر وانا برا الروم اوقف الموسيقى على الشخص الي يسمع 
من خلال البتن

**Comment by N1R0tka** [comment]
سوف يتم العمل على حل هذه المشكله في تمام الغد انشاء الله.
