### ISSUE TITLE
مشكل

### ISSUE THREAD

**Issue by Moudhackerplanfree** [DevelopersSupportAR/rexom#19]
اما اغير حالة و الريفيكس.. على ريبل ايت و لما اسوي ران تتخلبط الكتابو وحدها

**Comment by N1R0tka** [comment]
> اما اغير حالة و الريفيكس.. على ريبل ايت و لما اسوي ران تتخلبط الكتابو وحدها

اتوقع المشكله بسبب سوء استعمال
