### ISSUE TITLE
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.

### ISSUE THREAD

**Issue by ItsDaNZy** [DevelopersSupportAR/rexom#2]
hey!.
I made everything right but I always get this error  `Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted`

this a image for the page: https://i.imgur.com/RVLY9K8.png

**Comment by NASR51777** [comment]
نفس المشكلة الي عندي

**Comment by N1R0tka** [comment]
تمام هو حضرتك مفعل الخيارين دول 
![Screenshot_2021-09-22-16-56-31-90_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/85079850/134368206-1baa7496-5391-411c-8487-a08089b7030c.jpg)

**Comment by ItsDaNZy** [comment]
تمام يسطا البوت اشتغل وكلو تمام بس لما بحط بلاي ليست من اسبوتيفاي مثلا يعني عشر اغاني البوت كلو بيقف

**Comment by N1R0tka** [comment]
> تمام يسطا البوت اشتغل وكلو تمام بس لما بحط بلاي ليست من اسبوتيفاي مثلا يعني عشر اغاني البوت كلو بيقف

للأسف البوت لسه مش بيدعم سبوتي فاي بشكل كلي مع الوقت هينزل تحديثات و هتتحل المشكله

**Comment by ItsDaNZy** [comment]
تمام يسطا عاش علي البوت وياريت تعمل بوت حمايه جديد علشان مش لاقي القديم الي انت كنت عملو وشكرا ليك وكمل يسطا في اليوتيوب وشكرا

**Comment by y9lng** [comment]
م يستجيب عندي على الاوامر العادية بس شغال بالسلاش
