### ISSUE TITLE
error البوت جالس يوقف لحاله

### ISSUE THREAD

**Issue by nassimTN** [DevelopersSupportAR/rexom#25]
عندي بوق لما أشغل البوت و احط لينك ابتايم روبوت بعد كم وقت يفصل
![image](https://user-images.githubusercontent.com/93548810/139727732-535f2e2e-1a8a-461d-842c-4a39752b6360.png)
![image](https://user-images.githubusercontent.com/93548810/139727734-7459755a-d6a5-40a5-929a-ad4c21b9be87.png)

**Comment by N1R0tka** [comment]
Him @nassimTN 

please give's us more information like the full error (white words)
but it seems like a bad using for the bot or invalid config values
