### ISSUE TITLE
INVALID OAUTH2 REDIRECT_URI

### ISSUE THREAD

**Issue by ZIADMOHMED** [DevelopersSupportAR/rexom#27]
لما ادوس نيو تاب و اجي ادخل على ريكسوم و ادوس لوج ان يطلعلي كدة     INVALID OAUTH2 REDIRECT_URI

**Comment by Krypton000** [comment]
#### HI, @ZIADMOHMED ✋ 

I am sorry but maybe I don't correctly understand because I don't understand Arabic
but I think you forget to add the redirect URLs in **rexom** the only redirect URL is "url+/callback"
