### ISSUE TITLE
DisTubeError [NO_QUEUE]: There is no playing queue in this guild

### ISSUE THREAD

**Issue by blackmember4** [DevelopersSupportAR/rexom#3]

**Comment by N1R0tka** [comment]
> _No description provided._

Can you explain from what command this error appears?

If this error was from the Play command buttons, this error has been resolved, just copy the project from here: https://github.com/DevelopersSupportAR/rexom.git

**Comment by blackmember4** [comment]
> > _No description provided._
> 
> Can you explain from what command this error appears?
> 
> If this error was from the Play command buttons, this error has been resolved, just copy the project from here: https://github.com/DevelopersSupportAR/rexom.git

No is the ending song then error 
It was only when playing a single song.

**Comment by N1R0tka** [comment]
> > > _No description provided._
> > 
> > 
> > Can you explain from what command this error appears?
> > If this error was from the Play command buttons, this error has been resolved, just copy the project from here: https://github.com/DevelopersSupportAR/rexom.git
> 
> No is the ending song then error
> It was only when playing a single song.

Actually, it seems to me that the error is only yours, just try copying the project again and make sure the two options shown in the image below are enabled

`You have changed a lot of things in the past so make sure you have the latest version of the project`

**Comment by Stevenalbjwaya** [comment]
Hi
