### ISSUE TITLE
Error: Cannot find module '../core'

### ISSUE THREAD

**Issue by TheMickeyz** [DevelopersSupportAR/rexom#8]
Excuse me, can u help me this problem?

![image](https://user-images.githubusercontent.com/41478048/135534077-be02a174-c7ad-405e-a346-d30e6548be12.png)

Thank you

**Comment by N1R0tka** [comment]
> Excuse me, can u help me this problem?
> 
> ![image](https://user-images.githubusercontent.com/41478048/135534077-be02a174-c7ad-405e-a346-d30e6548be12.png)
> 
> Thank you

did u install the node_modules?

**Comment by TheMickeyz** [comment]
Yes, i'm already installed node_modules!

**Comment by TheMickeyz** [comment]
It's working! I'm install Distube node_modules again!
