### ISSUE TITLE
error in slashcommand

### ISSUE THREAD

**Issue by medofg1** [DevelopersSupportAR/rexom#9]
![Screenshot_1](https://user-images.githubusercontent.com/55420033/135747101-793f98f3-c161-4781-9102-938152c7e47a.png)

**Comment by medofg1** [comment]
+ البوت كل مايشغل اغنية يرجع نسبة الصوت 100 مايخليها زي ماخليتها قبل

**Comment by N1R0tka** [comment]
> * البوت كل مايشغل اغنية يرجع نسبة الصوت 100 مايخليها زي ماخليتها قبل

هادي ميزه في البوت

**Comment by N1R0tka** [comment]
هادي مشكله من عندك بسبب خطأ في الديسكورد  جي اس
عندك حين يا تضرد البوت و ترجع تدخله بصليحات ال سلاش كوماند
او تصبر شوي و تجرب تاني

**Comment by medofg1** [comment]
> * البوت كل مايشغل اغنية يرجع نسبة الصوت 100 مايخليها زي ماخليتها قبل

لا مو ميزة مزعجه كل شوي ترجع تخفض مستوى الصوت كل بوتات الميوزك البريميوم والمو بريميوم يبقى الصوت حتى لو سويت ستوب ترا مهمه هالميزة ياريت تسويها بالأيام القادمة وشكرا لك على كل شي
